const patterns = [
  {
    name: 'Glider',
    pattern: [
      [true, true, true],
      [true, false, false],
      [false, true, false],
    ],
  },
  {
    name: 'Lightweight Spaceship',
    pattern: [
      [false, true, true, true],
      [true, false, false, true],
      [false, false, false, true],
      [false, false, false, true],
      [true, false, true, false],
    ],
  },
  {
    name: 'Mediumweight Spaceship',
    pattern: [
      [false, false, true, true, true],
      [false, true, false, false, true],
      [false, false, false, false, true],
      [true, false, false, false, true],
      [false, false, false, false, true],
      [false, true, false, true, false],
    ],
  },
  {
    name: 'Heavyweight Spaceship',
    pattern: [
      [false, false, true, true, true],
      [false, true, false, false, true],
      [false, false, false, false, true],
      [true, false, false, false, true],
      [true, false, false, false, true],
      [false, false, false, false, true],
      [false, true, false, true, false],
    ],
  },
  {
    name: 'Glider Gun',
    pattern: [
      [false, false, false, false, true, true, false, false, false],
      [false, false, false, false, true, true, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, true, true, true, false, false],
      [false, false, false, true, false, false, false, true, false],
      [false, false, true, false, false, false, false, false, true],
      [false, false, true, false, false, false, false, false, true],
      [false, false, false, false, false, true, false, false, false],
      [false, false, false, true, false, false, false, true, false],
      [false, false, false, false, true, true, true, false, false],
      [false, false, false, false, false, true, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, true, true, true, false, false, false, false],
      [false, false, true, true, true, false, false, false, false],
      [false, true, false, false, false, true, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [true, true, false, false, false, true, true, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false, false, false],
      [false, false, true, true, false, false, false, false, false],
      [false, false, true, true, false, false, false, false, false],
    ],
  },
  {
    name: 'Switch Engine',
    pattern: [
      [false, true, false, false],
      [true, false, true, false],
      [false, false, false, false],
      [true, false, false, true],
      [false, false, true, true],
      [false, false, false, true],
    ],
  },
];

export default patterns;
